#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source /opt/boxen/env.sh

export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# Load Brew ZSH completions
fpath=(/opt/boxen/homebrew/share/zsh-completions $fpath)
